### PR TITLE
Adding custom commands for XebiaLabs Deployit

### PR DESCRIPTION
**Pull request by demobox**
Feedback and suggestions welcome! I suspect there may be some discussion e.g. about defaulting to a command with a parameter, rather than expecting the executable to be on the agent's `PATH` ;-)

### CODE REVIEW

**Comment by goteam** [comment]
Thanks for this and the nice article via moreinfo. Merging this assuming you have tested it with a running Go-Server.

**Comment by demobox** [comment]
> Merging this assuming you have tested it with a running Go-Server.

Some screenshots from local testing attached.
deployit-tasks
deployit-publish
deployit-deploy
deployit-publish-and-deploy

**Comment by goteam** [comment]
LOL. I meant tested the actual intergration (API calls) between Go and Deployit.

**Comment by demobox** [comment]
> LOL. I meant tested the actual intergration (API calls) between Go and Deployit.

Ah, like so! Yes, those were of course tested and, if anything changes, a follow up PR will be submitted.

Now we have some pretty pictures, too! ;-)

**Pull request merged**
